
version: 2

template_model_config: &model_config
  config:
    database: mike_temp
    schema: test

models:
    - name: my_first_dbt_model
      <<: *model_config
      description: "A starter dbt model"
      columns:
          - name: id

    - name: my_second_dbt_model
      description: "A starter dbt model"
      <<: *model_config
      columns:
          - name: id
        

